#!/usr/bin/env sh

# see https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing

docker build \
--build-arg VCS_REF="$(git rev-parse HEAD)" \
--build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
--build-arg VERSION="$(git describe --tags --always)" \
--tag ${IMAGE_NAME} .
